name: publish
on:
  push:
    paths:
      - 'debian/changelog'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: "ruby"
      - run: |
          major_version=$(head -n1 ruby/debian/changelog | egrep -o "ruby[0-9.]+" | sed "s/ruby//")
          minor_version=$(head -n1 ruby/debian/changelog | egrep -o "\([0-9.]+" | sed "s/(//")
          curl https://cache.ruby-lang.org/pub/ruby/${major_version}/ruby-${minor_version}.tar.gz > ruby${major_version}_${minor_version}.orig.tar.gz
          # Remove this file itself to avoid generating a debian-changes file
          rm -rf ruby/.github
      - name: Publish PPA
        uses: maths22/publish-ppa-package@main
        with:
          repository: 'ppa:maths22/ruby-testing'
          gpg_private_key: ${{ secrets.PPA_GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.PPA_GPG_PASSPHRASE }}
          series: 'bionic focal jammy'
          pkgdir: '${{ github.workspace }}/ruby/'
